### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/sam_myelin_seg_TEM#15]
This is a general overview of what needs to be done in this project before moving on to other datasets. Currently, both the axon and myelin seg models outperform ivadomed, but the overall pipeline is not efficient and nnUNet still beats SAM.
- [ ] integrate "patch-based" training: similar to how we trained U-Nets, this would allow bigger batch sizes and would eventually allow for data augmentation. Ideally, implement this with the MONAI dataloader for easier dataAug integration
- [ ] merge axon and myelin image encoders (halves overall model size, allows parameter sharing, more efficient training pipeline); see #10. Eventually, all datasets would be aggregated and the image encoder would learn to process all modalities.
- [ ] implement multi-GPU training to further increase the batch size and be able to train longer
